build_test:
  image: node:lts-alpine
  stage: build
  before_script:
    - cp app/etc/env.production.js app/etc/env.js
  script:
    - npm install
    - npm run compile
    - npm run build

demo_deploy:
  image: alpine
  stage: deploy
  only:
    - release
  before_script:
    - 'which ssh-agent || ( apk add --update openssh )'
    - eval $(ssh-agent -s)
    - echo "$DEMO_KEY" | base64 -d | ssh-add -
    - mkdir ~/.ssh
    - ssh-keyscan -H $DEMO_HOST >> ~/.ssh/known_hosts
  script:
    - ssh $DEMO_USER@$DEMO_HOST 'cd cattr/demo && docker-compose build --no-cache --force-rm demo'
    - ssh $DEMO_USER@$DEMO_HOST 'cd cattr/demo && docker-compose down -v && docker-compose up -d demo'

live_deploy:
  image: alpine
  stage: deploy
  only:
    - pre-release
  before_script:
    - 'which ssh-agent || ( apk add --update openssh )'
    - eval $(ssh-agent -s)
    - echo "$CI_KEY" | base64 -d | ssh-add -
    - mkdir ~/.ssh
    - ssh-keyscan -H $CI_HOST >> ~/.ssh/known_hosts
  script:
    - ssh $CI_USER@$CI_HOST 'cd cattr/frontend && git pull'
    - ssh $CI_USER@$CI_HOST 'cd cattr/frontend && git submodule update --init --force'
    - ssh $CI_USER@$CI_HOST 'source .zshrc && cd cattr/frontend && npm install'
    - ssh $CI_USER@$CI_HOST 'source .zshrc && cd cattr/frontend && npm run compile'
    - ssh $CI_USER@$CI_HOST 'source .zshrc && cd cattr/frontend && npm run clean'
    - ssh $CI_USER@$CI_HOST 'source .zshrc && cd cattr/frontend && npm run build'
    - ssh $CI_USER@$CI_HOST 'cd cattr/frontend && sentry-cli releases deploys `cat package.json | grep version | grep -o ":.*" | grep -o "\".*\"" | sed "s/\"//g"` new -e "production"'

staging_deploy:
  image: alpine
  stage: deploy
  only:
    - staging
  before_script:
    - 'which ssh-agent || ( apk add --update openssh )'
    - eval $(ssh-agent -s)
    - echo "$STAGING_KEY" | base64 -d | ssh-add -
    - mkdir ~/.ssh
    - ssh-keyscan -H $STAGING_HOST >> ~/.ssh/known_hosts
  script:
    - ssh $STAGING_USER@$STAGING_HOST 'cd frontend && git pull'
    - ssh $STAGING_USER@$STAGING_HOST 'cd frontend && git submodule update --init --force'
    - ssh $STAGING_USER@$STAGING_HOST 'cp -f frontend/app/etc/env.staging.js frontend/app/etc/env.js'
    - ssh $STAGING_USER@$STAGING_HOST 'source .zshrc && cd frontend && npm install'
    - ssh $STAGING_USER@$STAGING_HOST 'source .zshrc && cd frontend && npm run compile'
    - ssh $STAGING_USER@$STAGING_HOST 'source .zshrc && cd frontend && npm run clean'
    - ssh $STAGING_USER@$STAGING_HOST 'source .zshrc && cd frontend && npm run build'
    - ssh $STAGING_USER@$STAGING_HOST 'cd frontend && sentry-cli releases deploys `cat package.json | grep version | grep -o ":.*" | grep -o "\".*\"" | sed "s/\"//g"` new -e "staging"'

npm_publish:
  image: node:lts-alpine
  stage: publish
  only:
    - tags
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
    - npm publish --access=public

stages:
  - build
  - deploy
  - publish
